package net.sascha123789.djava.core.discord.types.guilds;

public enum GuildFeature {
    ANIMATED_BANNER("ANIMATED_BANNER"), ANIMATED_ICON("ANIMATED_ICON"), APPLICATION_COMMAND_PERMISSIONS_V2("APPLICATION_COMMAND_PERMISSIONS_V2"), AUTO_MODERATION("AUTO_MODERATION"), BANNER("BANNER"), COMMUNITY("COMMUNITY"), DEVELOPER_SUPPORT_SERVER("DEVELOPER_SUPPORT_SERVER"), DISCOVERABLE("DISCOVERABLE"), FEATURABLE("FEATURABLE"), INVITES_DISABLED("INVITES_DISABLED"), INVITE_SPLASH("INVITE_SPLASH"), MEMBER_VERIFICATION_GATE_ENABLED("MEMBER_VERIFICATION_GATE_ENABLED"), MONETIZATION_ENABLED("MONETIZATION_ENABLED"), MORE_STICKERS("MORE_STICKERS"), NEWS("NEWS"), PARTNERED("PARTNERED"), PREVIEW_ENABLED("PREVIEW_ENABLED"), ROLE_ICONS("ROLE_ICONS"), TICKETED_EVENTS_ENABLED("TICKETED_EVENTS_ENABLED"), VANITY_URL("VANITY_URL"), VERIFIED("VERIFIED"), VIP_REGIONS("VIP_REGIONS"), WELCOME_SCREEN_ENABLED("WELCOME_SCREEN_ENABLED");

    private String name;
    private GuildFeature(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
